# Generated by Django 5.0.6 on 2024-07-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_comment_text_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='immage_picture',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
