# Generated by Django 5.0.6 on 2024-07-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_immage_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='immage_picture',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='books/'),
            preserve_default=False,
        ),
    ]
