# Generated by Django 5.0.6 on 2024-07-04 17:48

import book.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_immage_picture_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to=book.helpers.Change_name.change),
        ),
    ]
